SOURCE_REPLICA_FOLDERS_ERR = ">>> [{C}ERROR{NC}]: Source folder and replica folder must be different.\n"
SYNC_COMPLETED = (
    ">>> [{C1}SUCCESS{NC1}]: Synchronization from {src} folder to {dst} completed. Took {delta} ms.\n"
    ">>> [{C2}SYNC STATS{NC2}]:\n"
    "    - Files updated: {f_u}.\n"
    "    - Files created: {f_c}.\n"
    "    - Files deleted: {f_r}.\n"
    "    - Directories created: {d_c}.\n"
    "    - Directories deleted: {d_r}.\n"
    ">>> [{C2}INFO{NC2}]: Next synchronization in aprox. {interval} seconds.\n\n"
)
SOURCE_FOLDER_NOT_EXISTS = ">>> [{C}WARNING{NC}]: Source {dir} folder does not exist.\n"
SOURCE_FOLDER_EMPTY = ">>> [{C}WARNING{NC}]: Source {dir} folder is empty.\n"
SOURCE_FOLDER_CREATED = ">>> [{C}INFO{NC}]: Created source {dir} folder.\n"
REPLICA_FOLDER_CREATED = ">>> [{C}INFO{NC}]: Created replica {dir} folder.\n"
FILE_CREATED = ">>> [{C}INFO{NC}]: Created new file {file} in replica {dir} folder.\n"
FILE_UPDATED = ">>> [{C}INFO{NC}]: Updated file {file} in replica {dir} folder.\n"
FILE_REMOVED = ">>> [{C}INFO{NC}]: Removed file {file} from replica {dir} folder.\n"
SUBDIR_CREATED = ">>> [{C}INFO{NC}]: Created new subdirectory {file} in replica {dir} folder.\n"
SUBDIR_REMOVED = ">>> [{C}INFO{NC}]: Removed subdirectory {file} from replica {dir} folder.\n"
